export enum AgeGroup {
  UNDER_13 = "UNDER_13",
  AGE_13_15 = "AGE_13_15",
  AGE_16_17 = "AGE_16_17",
  AGE_18_24 = "AGE_18_24",
  AGE_25_39 = "AGE_25_39",
  AGE_40_59 = "AGE_40_59",
  AGE_60_PLUS = "AGE_60_PLUS",
}

export enum ThoughtType {
  THOUGHT = "THOUGHT",
  QUESTION = "QUESTION",
  IDEA = "IDEA",
  MOMENT = "MOMENT",
}

export enum FeedVibe {
  CALM = "CALM",
  CURIOUS = "CURIOUS",
  LOCAL = "LOCAL",
  GLOBAL = "GLOBAL",
  PROFESSIONAL = "PROFESSIONAL",
  CREATIVE = "CREATIVE",
  FAMILY_FRIENDLY = "FAMILY_FRIENDLY",
}

export enum ReactionType {
  APPRECIATE = "APPRECIATE",
  USEFUL = "USEFUL",
  INTERESTING = "INTERESTING",
  LEARNED_SOMETHING = "LEARNED_SOMETHING",
  RELATE = "RELATE",
  DISAGREE = "DISAGREE",
}

export enum ShareIntent {
  AGREE = "AGREE",
  DISAGREE = "DISAGREE",
  USEFUL = "USEFUL",
  INTERESTING = "INTERESTING",
  ASKING_QUESTION = "ASKING_QUESTION",
  ADDING_CONTEXT = "ADDING_CONTEXT",
}

export enum ContentProvenance {
  HUMAN_AUTHORED = "HUMAN_AUTHORED",
  AI_ASSISTED = "AI_ASSISTED",
  AI_GENERATED = "AI_GENERATED",
  EDITED_FROM_AI = "EDITED_FROM_AI",
  UNKNOWN = "UNKNOWN",
}

export enum ContentClassification {
  OPINION = "OPINION",
  PERSONAL_EXPERIENCE = "PERSONAL_EXPERIENCE",
  CLAIM = "CLAIM",
  EVIDENCE_BACKED = "EVIDENCE_BACKED",
  UNRESOLVED = "UNRESOLVED",
}

export enum ModerationLayer {
  ILLEGAL = "ILLEGAL",
  DANGEROUS_INTERACTION = "DANGEROUS_INTERACTION",
  MANIPULATION = "MANIPULATION",
  MISINFORMATION_RISK = "MISINFORMATION_RISK",
  ORDINARY_DISAGREEMENT = "ORDINARY_DISAGREEMENT",
  CLEAN = "CLEAN",
}

export enum ModerationAction {
  BLOCK = "BLOCK",
  QUARANTINE = "QUARANTINE",
  REDUCE_AMPLIFICATION = "REDUCE_AMPLIFICATION",
  ADD_CONTEXT = "ADD_CONTEXT",
  ALLOW = "ALLOW",
  ESCALATE = "ESCALATE",
}

export enum ReportCategory {
  SCAM = "SCAM",
  HARASSMENT = "HARASSMENT",
  DOXXING = "DOXXING",
  CHILD_SAFETY = "CHILD_SAFETY",
  INTIMATE_IMAGE_ABUSE = "INTIMATE_IMAGE_ABUSE",
  IMPERSONATION = "IMPERSONATION",
  MISINFORMATION = "MISINFORMATION",
  SPAM = "SPAM",
  VIOLENCE = "VIOLENCE",
  SELF_HARM = "SELF_HARM",
  OTHER = "OTHER",
}

export enum AccountStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  DEACTIVATED = "DEACTIVATED",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
}

export enum Language {
  ENGLISH = "en",
  MANDARIN = "zh",
  MALAY = "ms",
  TAMIL = "ta",
}

export enum TrustSignal {
  HUMAN_VERIFIED = "HUMAN_VERIFIED",
  ACCOUNT_ESTABLISHED = "ACCOUNT_ESTABLISHED",
  SOURCES_FREQUENTLY_PROVIDED = "SOURCES_FREQUENTLY_PROVIDED",
  COMMUNITY_MEMBER = "COMMUNITY_MEMBER",
  ORGANISATION_VERIFIED = "ORGANISATION_VERIFIED",
}

export enum UIMode {
  STANDARD = "STANDARD",
  CHILD = "CHILD",
  SENIOR = "SENIOR",
  SIMPLE = "SIMPLE",
}
